from typing import Protocol, Dict, List, Any, Tuple

class ExportPort(Protocol):
    def generate_single_toxin_excel(self, residue_data: List[Dict], metadata: Dict[str, Any], toxin_name: str, source: str) -> Tuple[bytes, str]: ...
    def generate_family_excel(self, toxin_dataframes: Dict[str, Any], family_prefix: str, metadata: Dict[str, Any], export_type: str = 'residues', granularity: str = 'CA') -> Tuple[bytes, str]: ...
    def generate_comparison_excel(self, comparison_dataframes: Dict[str, Any], wt_family: str, metadata: Dict[str, Any], export_type: str = 'residues', granularity: str = 'CA') -> Tuple[bytes, str]: ...
