from typing import Protocol, List, Tuple, Optional, Dict, Any

class ToxinRepository(Protocol):
    def list_toxins(self) -> List[Tuple[int, str]]: ...
    def list_nav1_7(self) -> List[Tuple[int, str]]: ...
    def get_pdb(self, source: str, peptide_id: int) -> Optional[bytes]: ...
    def get_complete(self, source: str, peptide_id: int) -> Optional[Dict[str, Any]]: ...

class FamilyRepository(Protocol):
    def list_family_toxins(self, family_prefix: str) -> List[Tuple[int, str, Optional[float], Optional[str]]]: ...
    def list_family_peptides(self, family_prefix: str) -> List[Dict[str, Any]]: ...

class StructureRepository(Protocol):
    def get_pdb(self, source: str, peptide_id: int) -> Optional[bytes]: ...
    def get_psf(self, source: str, peptide_id: int) -> Optional[bytes]: ...

class MetadataRepository(Protocol):
    def get_toxin_info(self, source: str, peptide_id: int) -> Optional[Tuple[str, Optional[float], Optional[str]]]: ...
    def get_complete_toxin_data(self, source: str, peptide_id: int) -> Optional[Dict[str, Any]]: ...
    def get_family_toxins(self, family_prefix: str) -> List[Tuple[int, str, Optional[float], Optional[str]]]: ...
    def get_family_peptides(self, family_prefix: str) -> List[Dict[str, Any]]: ...
    def get_wt_toxin_data(self, peptide_code: str) -> Optional[Dict[str, Any]]: ...
